run:
  skip-dirs:
      - docs
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - gofmt
    - gofumpt
    - revive

linters-settings:
  revive:
    severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
